export const GroceriesFilterMock = [
    {name:"Cups, Mugs & more"},
 {name:"Gardening"},
{name:"Herbal & Ayurvedic"},
 {name:"Cookware & Non Stick"},
 {name:"Interior care"},
 {name:"Wall Decor"},
 {name:"Containers & Storage"},
 {name:"Hooks, Clips & Hangers"},
 {name:"Bedsheets"},
{name:"Sporting Equipment & Accessories"},
 {name:"Cloth Diapers"},
 {name:"Health Supplements"},
 {name:"Pillow & Pillow Covers"},
 {name:"Essential Kitchen Tools"},
 {name:"Artwork"},
 {name:"Home Decor Accents"},
 {name:"Backpacks & Bags"},
 {name:"Sports Nutrition"},
 {name:"Dinnerware"},
 {name:"Flask & Bottle"},
 {name:"Paint & Exterior care"},
 {name:"Laundry Accessories"},
 {name:"Body Supports"},
 {name:"Mats"},
 {name:"Towels"},
 {name:"Tableware"},
 {name:"Namkeen & Savoury Snacks"},
 {name:"Curtains & Accessories"},
 {name:"Dog Accessories"},
 {name:"Table & Kitchen Linen"},
 {name:"Dog Grooming"},
 {name:"Whole Spices"},
 {name:"Other Stationery"},
 {name:"Bathroom Accessories"},
 {name:"Insect & Animal Control"},
 {name:"Face Care"},
 {name:"Learning & Education"},
 {name:"Travel Accessories"},
 {name:"Dog Toys"},
 {name:"Powdered Spices"},
 {name:"Office Supplies"},
{name:"Early Learning"},
 {name:"Bed Protector"},
 {name:"Safety accessories"},
 {name:"History"},
 {name:"Cricket"},
 {name:"Artificial Flora"},
 {name:"Dried Seeds"},
 {name:"Shampoo & Conditioner"},
        ];